name: "Hello Actions"
description: "Greet someone"
author: "ldtoan@github.com"

input:
  My_name:
    description: "who to greet"
    required: true
    default: "World"
  
  runs:
    using: "docker"
    image: "Dockerfile"
  
  branding:
    icon: "mic"
    color: "purple"
